export type CurrencyOption = {
  value: string;
  label: string;
};

export const currencies: CurrencyOption[] = [
  { value: "USD", label: "USD - US Dollar" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "KRW", label: "KRW - South Korean Won" },

  // Extended list 🌍
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "PLN", label: "PLN - Polish Zloty" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "ILS", label: "ILS - Israeli Shekel" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "MMK", label: "MMK - Myanmar Kyat" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "UYU", label: "UYU - Uruguayan Peso" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "TND", label: "TND - Tunisian Dinar" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "TZS", label: "TZS - Tanzanian Shilling" },
  { value: "UGX", label: "UGX - Ugandan Shilling" },
  { value: "GHS", label: "GHS - Ghanaian Cedi" },
  { value: "ETB", label: "ETB - Ethiopian Birr" },
  { value: "XOF", label: "XOF - West African CFA Franc" },
  { value: "XAF", label: "XAF - Central African CFA Franc" },
  { value: "BWP", label: "BWP - Botswana Pula" },
  { value: "MUR", label: "MUR - Mauritian Rupee" },
  { value: "SCR", label: "SCR - Seychellois Rupee" },
  { value: "FJD", label: "FJD - Fijian Dollar" },
  { value: "PGK", label: "PGK - Papua New Guinean Kina" },
  { value: "WST", label: "WST - Samoan Tala" },
  { value: "TOP", label: "TOP - Tongan Paʻanga" },
  { value: "SBD", label: "SBD - Solomon Islands Dollar" },
  { value: "MNT", label: "MNT - Mongolian Tögrög" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "UZS", label: "UZS - Uzbekistani Som" },
  { value: "TMT", label: "TMT - Turkmenistani Manat" },
  { value: "AZN", label: "AZN - Azerbaijani Manat" },
  { value: "GEL", label: "GEL - Georgian Lari" },
  { value: "AMD", label: "AMD - Armenian Dram" },
  { value: "MDL", label: "MDL - Moldovan Leu" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "ISK", label: "ISK - Icelandic Krona" },
  { value: "MKD", label: "MKD - Macedonian Denar" },
  { value: "ALL", label: "ALL - Albanian Lek" },
  { value: "BAM", label: "BAM - Bosnia-Herzegovina Convertible Mark" }
];